spring.application.name=networkstream-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/networkstream}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:networkstream}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:networkstream}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health,info
